// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Caption = __t.object("Caption", {
  id: __t.string(),
  sessionId: __t.string(),
  text: __t.string(),
  createdAt: __t.u64(),
});
export type Caption = __Infer<typeof Caption>;

export const Intervention = __t.object("Intervention", {
  id: __t.string(),
  sessionId: __t.string(),
  message: __t.string(),
  suggestion: __t.string(),
  urgency: __t.string(),
  acknowledged: __t.bool(),
  createdAt: __t.u64(),
});
export type Intervention = __Infer<typeof Intervention>;

export const MoodWord = __t.object("MoodWord", {
  id: __t.string(),
  sessionId: __t.string(),
  word: __t.string(),
  audienceId: __t.string(),
  interventionId: __t.string(),
  createdAt: __t.u64(),
});
export type MoodWord = __Infer<typeof MoodWord>;

export const Poll = __t.object("Poll", {
  id: __t.string(),
  sessionId: __t.string(),
  question: __t.string(),
  options: __t.string(),
  votes: __t.string(),
  active: __t.bool(),
  createdAt: __t.u64(),
});
export type Poll = __Infer<typeof Poll>;

export const PollVote = __t.object("PollVote", {
  id: __t.string(),
  pollId: __t.string(),
  audienceId: __t.string(),
  option: __t.string(),
});
export type PollVote = __Infer<typeof PollVote>;

export const Question = __t.object("Question", {
  id: __t.string(),
  sessionId: __t.string(),
  text: __t.string(),
  audienceId: __t.string(),
  upvotes: __t.u32(),
  dismissed: __t.bool(),
  answered: __t.bool(),
  createdAt: __t.u64(),
});
export type Question = __Infer<typeof Question>;

export const QuestionUpvote = __t.object("QuestionUpvote", {
  id: __t.string(),
  questionId: __t.string(),
  audienceId: __t.string(),
});
export type QuestionUpvote = __Infer<typeof QuestionUpvote>;

export const RateLimit = __t.object("RateLimit", {
  key: __t.string(),
  lastAction: __t.u64(),
});
export type RateLimit = __Infer<typeof RateLimit>;

export const Session = __t.object("Session", {
  sessionId: __t.string(),
  speakerName: __t.string(),
  topic: __t.string(),
  createdAt: __t.u64(),
  active: __t.bool(),
});
export type Session = __Infer<typeof Session>;

export const Signal = __t.object("Signal", {
  id: __t.string(),
  sessionId: __t.string(),
  signalType: __t.string(),
  audienceId: __t.string(),
  fingerprint: __t.string(),
  weight: __t.f32(),
  createdAt: __t.u64(),
});
export type Signal = __Infer<typeof Signal>;

